Compile and run on Mac OS 15.1 (Sequoia)

diff --git a/compiler+runtime/bin/build-clang b/compiler+runtime/bin/build-clang
--- a/compiler+runtime/bin/build-clang
+++ b/compiler+runtime/bin/build-clang
@@ -10,28 +10,28 @@ make_j="$(nproc || echo 4)"
 
 while getopts ":hj:" opt; do
   case "${opt}" in
-    h)
-      echo "Usage ${0} [-j N] [srcdir]"
-      exit 0
-      ;;
-    j)
-      make_j="${OPTARG}"
-      ;;
-    \?)
-      echo "Invalid option: ${OPTARG}" 1>&2
-      exit 1
-      ;;
-    :)
-      echo "Invalid option: ${OPTARG} requires an argument" 1>&2
-      exit 1
-      ;;
-    *)
-      echo "Unexpected input: ${OPTARG}" 1>&2
-      exit 1
-      ;;
+  h)
+    echo "Usage ${0} [-j N] [srcdir]"
+    exit 0
+    ;;
+  j)
+    make_j="${OPTARG}"
+    ;;
+  \?)
+    echo "Invalid option: ${OPTARG}" 1>&2
+    exit 1
+    ;;
+  :)
+    echo "Invalid option: ${OPTARG} requires an argument" 1>&2
+    exit 1
+    ;;
+  *)
+    echo "Unexpected input: ${OPTARG}" 1>&2
+    exit 1
+    ;;
   esac
 done
-shift $((OPTIND -1))
+shift $((OPTIND - 1))
 
 echo "Using ${make_j} cores to build"
 
@@ -40,31 +40,29 @@ srcdir="${PWD}"
 llvm_url="https://github.com/jank-lang/llvm-project.git"
 llvm_branch="main"
 
-function prepare()
-{
-  if [[ ! -d "${srcdir}/llvm" ]];
-  then
+function prepare() {
+  if [[ ! -d "${srcdir}/llvm" ]]; then
     git clone -b "${llvm_branch}" --shallow-submodules --single-branch "${llvm_url}" "${srcdir}"/llvm
   fi
 }
 
-function build()
-{
+function build() {
   mkdir -p "${srcdir}/llvm-build"
   cd "${srcdir}/llvm-build"
 
   cmake -DCMAKE_BUILD_TYPE=Release \
-        -DCMAKE_CXX_STANDARD=20 \
-        -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" \
-        -DLLVM_TARGETS_TO_BUILD="host" \
-        -DLLVM_ENABLE_EH=OFF \
-        -DLLVM_ENABLE_RTTI=OFF \
-        -DLLVM_INCLUDE_BENCHMARKS=OFF \
-        -DLLVM_INCLUDE_EXAMPLES=OFF \
-        -DLLVM_INCLUDE_TESTS=OFF \
-        -DLLVM_ENABLE_ZSTD=OFF \
-        -G "Unix Makefiles" \
-        ../llvm/llvm
+    -DLLVM_ENABLE_RUNTIMES=all \
+    -DCMAKE_CXX_STANDARD=20 \
+    -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" \
+    -DLLVM_TARGETS_TO_BUILD="host" \
+    -DLLVM_ENABLE_EH=OFF \
+    -DLLVM_ENABLE_RTTI=OFF \
+    -DLLVM_INCLUDE_BENCHMARKS=OFF \
+    -DLLVM_INCLUDE_EXAMPLES=OFF \
+    -DLLVM_INCLUDE_TESTS=OFF \
+    -DLLVM_ENABLE_ZSTD=OFF \
+    -G "Unix Makefiles" \
+    ../llvm/llvm
 
   DESTDIR="${srcdir}/llvm-install" make clang clang-repl clang-cpp clang-tidy install -j"${make_j}"
 }
